poses_dir: /home/nicholscrawfordtaylor/Experiments/NLPGoals/sampling/poses
pointclouds_dir: /home/nicholscrawfordtaylor/Experiments/NLPGoals/sampling/pointclouds
# uniform
# model_dir: /home/nicholscrawfordtaylor/Experiments/NLPGoals/diffusion_experiments/2023_06_14-13:51:35/lightning_logs/version_0/checkpoints/epoch=267-step=82276.ckpt
model_dir: /home/nicholscrawfordtaylor/Experiments/NLPGoals/diffusion_experiments/2023_06_19-14:03:52/lightning_logs/version_0/checkpoints/epoch=19-step=640.ckpt

random_seed: 1
device: 0

dataset:
  batch_size: 16
  num_workers: 0
  pin_memory: True

sampling:
  ddim: True
  ddim_steps: 3
  guidance_sampling: True
  forward_universal_guidance: True
  guidance_strength_factor: 10
  backward_universal_guidance: True
  backwards_steps_m: 20
  backward_guidance_lr: 0.05
  per_step_self_recurrance: True
  per_step_k: 4

  clip_model: ViT-B/32
  embedder_checkpoint_path: /home/nicholscrawfordtaylor/Experiments/NLPGoals/embedder_experiments/sorta_works/lightning_logs/version_49970/checkpoints/epoch=352-step=434896.ckpt
  labels:
    - a set of objects placed in a line




