experiment_dir: /home/nicholscrawfordtaylor/Experiments/NLPGoals/diffusion_experiments/${oc.env:DATETIME}

random_seed: 1


dataset:
  train_dirs:
    #- /home/nicholscrawfordtaylor/data/jun5_structs/
    #- /home/nicholscrawfordtaylor/data/jun7_structs/
    - /home/nicholscrawfordtaylor/data/jun8_simple_circles
  valid_dirs:
    #- /home/nicholscrawfordtaylor/data/jun6_structs/
    - /home/nicholscrawfordtaylor/data/jun8_simple_circles_val
  batch_size: 32
 
  num_pts: 256

  num_workers: 6
  pin_memory: True
  shuffle_object_index: False

model:
  name: transformer_diffuser
  num_attention_heads: 8
  encoder_hidden_dim: 512
  encoder_dropout: 0.0
  encoder_activation: relu
  encoder_num_layers: 8
  object_dropout: 0


training:
  learning_rate: 0.0001
  max_epochs: 500
  l2: 0  #0.0001
  # lr_restart: 3000
  # warmup: 10

diffusion:
  time_steps: 200
  loss_type: huber
