experiment_dir: /home/nicholscrawfordtaylor/Experiments/NLPGoals/embedder_experiments/jul4/${oc.env:DATETIME}

random_seed: 1
device: cuda

clip_model: "ViT-B/32"

dataset:
  train_dirs:
    - /home/nicholscrawfordtaylor/data/NaturalLanguagePlanningGoals/jul4
  valid_dirs:
    - /home/nicholscrawfordtaylor/data/NaturalLanguagePlanningGoals/jul4_val
  batch_size: 32
  num_workers: 7

training:
  max_epochs: 1000 # 1000 # Found in first experiement training up to 210 to get basically all the benefit. Was with mse loss.
